# generated by datamodel-codegen:
#   filename:  tenant-registration.bundled.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class A2ARuntimeTenantRegistrationV1(RootModel[Any]):
    root: Any = Field(..., title='A2A runtime tenant registration (v1)')
    """
    The RUNTIME tenant registry contract (added in contract v1.3.0). Until now the shared A2A server resolved its tenant set from the STATIC `a2a.tenants[]` array in the chart's values (values-interface.schema.json), rendered to a ConfigMap the server read at boot, and an initContainer cloned each tenant repo so the server could PROJECT the card. This file freezes the shapes for the alternative topology decided in izzywdev/FuzeAgent#203: consumers SELF-REGISTER at runtime into a DB registry owned by the orchestrator, PUSH their already-projected Agent Card as data, and the stateless/DB-free A2A server fetches the resolved set over HTTP. 

    This is PURELY ADDITIVE to v1. It does not remove, rename or re-type any field of values-interface.schema.json — the static `a2a.tenants[]` topology is unchanged and remains valid; a deployment that never calls these endpoints behaves exactly as before. 

    Three shapes are frozen here as `$defs`: `RegisteredTenant` (the canonical `a2a_tenants` record — the row the Slice-1 migration creates and the row the Slice-3 server reader consumes, frozen ONCE here so the DB, the orchestrator writer and the server reader all target the same shape), `RegisterTenantRequest` (the self-registration payload) and `RegisterTenantResponse` (the upsert result), plus the `TenantList` read response. The two orchestrator HTTP operations that carry these shapes, their idempotent-upsert semantics, the OIDC self-registration security rule and the card-validation rule are NORMATIVE in tenant-registration.md — read it alongside this schema.

    The `card` field REUSES the frozen agent-card.schema.json BY REFERENCE and is NOT redefined here: the projected card that arrives via registration is byte-identical to the card the generator used to project from a cloned repo. A pushed card MUST additionally satisfy fuze-profile.schema.json (signed, single JSONRPC interface, etc.) exactly as a served card does today — a structural agent-card is necessary but not sufficient; see tenant-registration.md §4.
    """


class TenantSlug(RootModel[constr(pattern=r'^[A-Za-z0-9_-]+$')]):
    root: constr(pattern=r'^[A-Za-z0-9_-]+$')
    """
    The tenant routing key AND the unique registry key (the record's natural id — there is no separate minted uuid; identifier-standard §4.2 client-assigned-id is `allowed` for exactly this reason, see RegisterTenantRequest). MUST equal the card's `supportedInterfaces[].tenant` (card-projection.md §2) and, for the self-registration security rule, MUST be derivable from the authenticated caller repo (tenant-registration.md §3).
    """


class RepoName(RootModel[constr(pattern=r'^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')]):
    root: constr(pattern=r'^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')
    """
    owner/name of the repo whose manifest + roles were the projection source for `card`. Same shape as values-interface tenant.repo. For the self-registration rule this MUST match the authenticated caller identity (auth.callerClaim, authz.md §2).
    """


class RoleKey(RootModel[constr(pattern=r'^[a-z0-9_-]+$')]):
    root: constr(pattern=r'^[a-z0-9_-]+$')
    """
    A role key; the join key an adapter uses to resolve an incoming skill id back to a role (card-projection.md §3).
    """


class SecretRef(BaseModel):
    """
    Reference to an existing Kubernetes Secret (SealedSecret-provisioned). A REFERENCE only — secret VALUES never appear on the wire, in the registry, or in git (same rule as values-interface §secretRef).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    key: str


class Provider(BaseModel):
    """
    Managed-Agents runtime binding for THIS tenant's sessions (the values that reach agent-templates/providers/*). Mirrors values-interface tenant.provider; the consumer declares how ITS OWN sessions are provisioned. Secret material is by reference only (secretRef), never inline literals, and is NEVER projected onto the card.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = 'anthropic'
    """
    AgentProvider implementation id (base.py `name`).
    """
    environmentId: str | None = None
    """
    Environment the sessions bind to. Resolved from the role's `environment` when unset.
    """
    apiKeySecretRef: SecretRef | None = None
    vaultIds: list[str] | None = None
    """
    Vault ids passed to create_session. NEVER projected onto the card.
    """
    memoryResources: list[str] | None = None
    """
    Memory stores mounted into sessions (e.g. the shared handoff store).
    """


class ProtocolBinding(StrEnum):
    """
    Open string. Core values: JSONRPC, GRPC, HTTP+JSON. Fuze v1 permits only JSONRPC.
    """

    JSONRPC = 'JSONRPC'
    GRPC = 'GRPC'
    HTTP_JSON = 'HTTP+JSON'


class AgentInterface(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    """
    Absolute URL of this interface. In-cluster Fuze interfaces use service DNS (http://a2a-<repo>.fuzeagent.svc.cluster.local:8080/rpc); externally-published ones MUST be https:// through the Cloudflare tunnel.
    """
    protocolBinding: ProtocolBinding
    """
    Open string. Core values: JSONRPC, GRPC, HTTP+JSON. Fuze v1 permits only JSONRPC.
    """
    tenant: str | None = None
    """
    Opaque routing id when several agents sit behind one endpoint. The Fuze shared server sets this to the serving repo slug so one ingress can front many product agents. When set, clients MUST echo it in the request `tenant` field.
    """
    protocolVersion: constr(pattern=r'^\d+\.\d+$')
    """
    A2A protocol Major.Minor exposed at this URL (NOT the agent version). Fuze v1 freezes on "1.0".
    """


class AgentProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    organization: constr(min_length=1)


class AgentExtension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uri: AnyUrl
    description: str | None = None
    required: bool | None = None
    params: dict[str, Any] | None = None


class SecurityRequirement(RootModel[dict[str, list[str]]]):
    """
    Map of security scheme name -> list of required scopes.
    """

    root: dict[str, list[str]]


class Location(Enum):
    query = 'query'
    header = 'header'
    cookie = 'cookie'


class ApiKeySecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    location: Location
    name: str


class HttpAuthSecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    scheme: str
    bearerFormat: str | None = None


class Oauth2SecurityScheme(BaseModel):
    description: str | None = None
    flows: dict[str, Any]
    oauth2MetadataUrl: AnyUrl | None = None


class OpenIdConnectSecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    openIdConnectUrl: AnyUrl


class MtlsSecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None


class SecurityScheme(BaseModel):
    """
    ProtoJSON oneof wrapper — exactly one variant key.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiKeySecurityScheme: ApiKeySecurityScheme | None = None
    httpAuthSecurityScheme: HttpAuthSecurityScheme | None = None
    oauth2SecurityScheme: Oauth2SecurityScheme | None = None
    openIdConnectSecurityScheme: OpenIdConnectSecurityScheme | None = None
    mtlsSecurityScheme: MtlsSecurityScheme | None = None


class AgentCardSignature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protected: str
    """
    base64url-encoded protected JWS header.
    """
    signature: str
    """
    base64url-encoded signature.
    """
    header: dict[str, Any] | None = None


class AgentCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    streaming: bool | None = None
    pushNotifications: bool | None = None
    extendedAgentCard: bool | None = None
    extensions: list[AgentExtension] | None = None


class AgentSkill(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z0-9_-]+$')
    """
    MUST equal the `role` key of the source role.json. This is the join key that lets the adapter resolve a skill back to a role manifest.
    """
    name: constr(min_length=1)
    description: constr(min_length=1)
    tags: list[str] = Field(..., min_length=1)
    examples: list[str] | None = None
    inputModes: list[str] | None = None
    outputModes: list[str] | None = None
    securityRequirements: list[SecurityRequirement] | None = None


class AgentCard(BaseModel):
    """
    JSON Schema for the A2A AgentCard as served at /.well-known/agent-card.json. Faithful to the ProtoJSON (camelCase) serialization of message AgentCard in lf.a2a.v1 (a2a.proto, A2A spec 1.0.0). The `fuze` profile below adds REQUIRED family constraints on top of the open standard; a card that satisfies this schema is by construction a valid A2A 1.0 AgentCard.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    """
    Human readable agent name. Fuze projection: `<Repo> <role> agent`, e.g. 'FuzePlan planning agent'.
    """
    description: constr(min_length=1)
    """
    What this agent is for, in caller-facing terms. Callers route on this text, so it MUST describe outcomes the agent delivers, not the tools it holds.
    """
    supportedInterfaces: list[AgentInterface] = Field(..., min_length=1)
    """
    Ordered list of interfaces; the FIRST entry is the preferred one. A2A 1.0 replaced 0.x `url` + `preferredTransport` with this list — there is no top-level url field.
    """
    provider: AgentProvider
    version: constr(pattern=r'^\d+\.\d+\.\d+(?:[-+].*)?$')
    """
    Version OF THE AGENT (not of the A2A protocol). SemVer. Projected from the contract version of the serving repo's role set.
    """
    documentationUrl: AnyUrl | None = None
    iconUrl: AnyUrl | None = None
    capabilities: AgentCapabilities
    securitySchemes: dict[str, SecurityScheme] | None = Field(None, min_length=1)
    """
    Map of scheme name -> SecurityScheme. NOTE the ProtoJSON oneof wrapper: the value is an object with exactly one key naming the scheme variant (e.g. {"openIdConnectSecurityScheme": {...}}). This is NOT the OpenAPI securityScheme shape.
    """
    securityRequirements: list[SecurityRequirement] | None = None
    """
    Requirements for contacting the agent. Entries are OR'ed; schemes within an entry are AND'ed.
    """
    defaultInputModes: list[str] = Field(..., min_length=1)
    """
    Media types accepted across all skills. Fuze v1 baseline: ["text/plain", "application/json"].
    """
    defaultOutputModes: list[str] = Field(..., min_length=1)
    """
    Media types produced. Fuze v1 baseline: ["text/plain", "application/json"].
    """
    skills: list[AgentSkill] = Field(..., min_length=1)
    """
    DERIVED from agent-templates/roles/*/role.json. See card-projection.md. Hand-authoring skills is a contract violation.
    """
    signatures: list[AgentCardSignature] | None = None
    """
    JWS signatures over the canonicalized card (RFC 7515 JSON serialization). OPTIONAL in A2A; see the Fuze profile for when it is REQUIRED.
    """


class RegisterTenantRequest(BaseModel):
    """
    The self-registration payload a consumer PUSHes to `POST /a2a/tenants/register`. Carries the tenant identity, its routing/serving config and its already-projected Agent Card. The server assigns nothing except timestamps (createdAt/updatedAt live only on the stored RegisteredTenant, never in the request). SECURITY (normative, tenant-registration.md §3): `tenant` and `repo` MUST match the authenticated caller identity (the same `auth.callerClaim` the A2A server validates, authz.md §2); a payload whose tenant/repo differs from the credential is REJECTED (403) and never written.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tenant: TenantSlug
    repo: RepoName
    ref: str | None = 'main'
    """
    Git ref the manifest/roles the card was projected from were read at. Provenance for the pushed card; the server does NOT clone it.
    """
    entryRole: RoleKey
    """
    The role that serves a SendMessage naming no skill (mirrors values-interface tenant.entryRole / manifest.a2a.entryRole).
    """
    servingRoles: list[RoleKey] = Field(..., min_length=1)
    """
    The roles projected into card `skills`. Kept in the record so the adapter can resolve an incoming skill id back to a role; the card already encodes the skills but the join set is stored explicitly.
    """
    external: bool | None = False
    """
    Published through the Cloudflare tunnel with an https interface URL. MUST be false for exec-tier tenants (card-projection.md §5).
    """
    provider: Provider | None = None
    enabled: bool | None = True
    """
    Whether this tenant is served once registered. Self-registration intent is to be served, so it defaults true; the orchestrator may later disable a tenant without a re-register. Independent of the authz `providesTo` grant, which is still enforced fail-closed by the callee (authz.md §3) and is NOT set here.
    """
    card: AgentCard
    """
    The consumer's PROJECTED Agent Card, pushed as data (decision #2 of #203). Byte-identical to what the generator used to project from a cloned repo — this contract changes only HOW the card arrives, not what it looks like. Structurally an agent-card.schema.json card; the server MUST ADDITIONALLY validate it against fuze-profile.schema.json (non-empty signatures[], single JSONRPC/1.0 interface, capabilities constants) before storing — see tenant-registration.md §4. A card that fails either validation is REJECTED (422) and never written.
    """


class RegisteredTenant(BaseModel):
    """
    The canonical `a2a_tenants` registry record: the row the orchestrator stores and serves, the shape the Slice-1 DB migration targets and the Slice-3 A2A server reader consumes. Frozen ONCE here so DB, writer and reader cannot drift. It is the RegisterTenantRequest fields, fully defaulted, plus server-owned `createdAt`/`updatedAt`. `tenant` is the unique key.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tenant: TenantSlug
    repo: RepoName
    ref: str
    """
    Git ref the card was projected from (default `main` applied at registration).
    """
    entryRole: RoleKey
    servingRoles: list[RoleKey] = Field(..., min_length=1)
    external: bool
    """
    See RegisterTenantRequest.external.
    """
    provider: Provider | None = None
    enabled: bool
    """
    Whether the A2A server should serve this tenant. The read endpoint may filter on it; see tenant-registration.md §2.
    """
    card: AgentCard
    """
    The stored projected Agent Card. Validated against agent-card.schema.json AND fuze-profile.schema.json at registration.
    """
    createdAt: AwareDatetime
    """
    Server-set. ISO 8601, UTC, `Z` suffix. Set on first registration; unchanged by subsequent upserts.
    """
    updatedAt: AwareDatetime
    """
    Server-set. ISO 8601, UTC, `Z` suffix. Advanced on every upsert.
    """


class RegisterTenantResponse(BaseModel):
    """
    The result of `POST /a2a/tenants/register`. `created` distinguishes the two idempotent-upsert outcomes (201 first registration vs 200 update); `record` is the resolved stored row.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    created: bool
    """
    true when this call inserted a new tenant (HTTP 201); false when it updated an existing one (HTTP 200). See tenant-registration.md §2 for upsert semantics.
    """
    record: RegisteredTenant


class TenantList(BaseModel):
    """
    The response of `GET /a2a/tenants` — the full registered-tenant set the A2A server resolves. Not paginated (see x-pagination-reason).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tenants: list[RegisteredTenant]
    """
    All registered tenants. When `?enabled=true` is passed the server returns only enabled tenants (the default the A2A server uses); otherwise all rows are returned (operator view).
    """
    count: conint(ge=0) | None = None
    """
    Number of entries in `tenants` (convenience; equals tenants.length).
    """
