# generated by datamodel-codegen:
#   filename:  a2a-wire.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel, conint, constr


class A2AWireTypesJsonRpcBindingV1Subset(RootModel[Any]):
    root: Any = Field(..., title='A2A wire types (JSON-RPC binding, v1 subset)')
    """
    ProtoJSON (camelCase) serialization of the lf.a2a.v1 wire messages used by the Fuze v1 binding. Derived from the normative a2a.proto of A2A spec 1.0.0. Scope is the v1 method set from binding.md — push-notification config types are intentionally absent because those methods return PushNotificationNotSupportedError in v1.
    """


class TaskState(StrEnum):
    """
    ProtoJSON enum names. TASK_STATE_UNSPECIFIED MUST never be emitted by a Fuze agent.
    """

    TASK_STATE_UNSPECIFIED = 'TASK_STATE_UNSPECIFIED'
    TASK_STATE_SUBMITTED = 'TASK_STATE_SUBMITTED'
    TASK_STATE_WORKING = 'TASK_STATE_WORKING'
    TASK_STATE_COMPLETED = 'TASK_STATE_COMPLETED'
    TASK_STATE_FAILED = 'TASK_STATE_FAILED'
    TASK_STATE_CANCELED = 'TASK_STATE_CANCELED'
    TASK_STATE_INPUT_REQUIRED = 'TASK_STATE_INPUT_REQUIRED'
    TASK_STATE_REJECTED = 'TASK_STATE_REJECTED'
    TASK_STATE_AUTH_REQUIRED = 'TASK_STATE_AUTH_REQUIRED'


class Role(StrEnum):
    ROLE_UNSPECIFIED = 'ROLE_UNSPECIFIED'
    ROLE_USER = 'ROLE_USER'
    ROLE_AGENT = 'ROLE_AGENT'


class Part1(BaseModel):
    """
    Exactly one content variant. Fuze v1 accepts `text` and `data` on input; `url`/`raw` inputs return ContentTypeNotSupportedError (-32005).
    """

    text: str
    raw: str | None = Field(None, json_schema_extra={'contentEncoding': 'base64'})
    url: AnyUrl | None = None
    data: Any | None = None
    metadata: dict[str, Any] | None = None
    filename: str | None = None
    mediaType: str | None = None


class Part2(BaseModel):
    """
    Exactly one content variant. Fuze v1 accepts `text` and `data` on input; `url`/`raw` inputs return ContentTypeNotSupportedError (-32005).
    """

    text: str | None = None
    raw: str = Field(..., json_schema_extra={'contentEncoding': 'base64'})
    url: AnyUrl | None = None
    data: Any | None = None
    metadata: dict[str, Any] | None = None
    filename: str | None = None
    mediaType: str | None = None


class Part3(BaseModel):
    """
    Exactly one content variant. Fuze v1 accepts `text` and `data` on input; `url`/`raw` inputs return ContentTypeNotSupportedError (-32005).
    """

    text: str | None = None
    raw: str | None = Field(None, json_schema_extra={'contentEncoding': 'base64'})
    url: AnyUrl
    data: Any | None = None
    metadata: dict[str, Any] | None = None
    filename: str | None = None
    mediaType: str | None = None


class Part4(BaseModel):
    """
    Exactly one content variant. Fuze v1 accepts `text` and `data` on input; `url`/`raw` inputs return ContentTypeNotSupportedError (-32005).
    """

    text: str | None = None
    raw: str | None = Field(None, json_schema_extra={'contentEncoding': 'base64'})
    url: AnyUrl | None = None
    data: Any
    metadata: dict[str, Any] | None = None
    filename: str | None = None
    mediaType: str | None = None


class Part(RootModel[Part1 | Part2 | Part3 | Part4]):
    root: Part1 | Part2 | Part3 | Part4
    """
    Exactly one content variant. Fuze v1 accepts `text` and `data` on input; `url`/`raw` inputs return ContentTypeNotSupportedError (-32005).
    """


class Message(BaseModel):
    messageId: constr(min_length=1)
    contextId: str | None = None
    taskId: str | None = None
    """
    Present on a continuation. Its presence is what makes the adapter resume_session instead of create_session (state-mapping.md §2).
    """
    role: Role
    parts: list[Part] = Field(..., min_length=1)
    metadata: dict[str, Any] | None = None
    """
    NEVER trusted for authorization (authz.md §1).
    """
    extensions: list[str] | None = None
    referenceTaskIds: list[str] | None = None


class TaskStatus(BaseModel):
    state: TaskState
    message: Message | None = None
    """
    REQUIRED by the Fuze profile whenever state is INPUT_REQUIRED or AUTH_REQUIRED — it explains what is being asked and of whom.
    """
    timestamp: AwareDatetime | None = None
    """
    ISO 8601, UTC, Z suffix.
    """


class Artifact(BaseModel):
    artifactId: str
    """
    Stable across append chunks.
    """
    name: str | None = None
    description: str | None = None
    parts: list[Part] = Field(..., min_length=1)
    metadata: dict[str, Any] | None = None
    extensions: list[str] | None = None


class Task(BaseModel):
    id: str
    """
    IS the Managed-Agents session id (state-mapping.md §1).
    """
    contextId: str | None = None
    status: TaskStatus
    artifacts: list[Artifact] | None = None
    history: list[Message] | None = None
    metadata: dict[str, Any] | None = None


class TaskStatusUpdateEvent(BaseModel):
    taskId: str
    contextId: str
    status: TaskStatus
    metadata: dict[str, Any] | None = None


class TaskArtifactUpdateEvent(BaseModel):
    taskId: str
    contextId: str
    artifact: Artifact
    append: bool | None = None
    lastChunk: bool | None = None
    metadata: dict[str, Any] | None = None


class SendMessageConfiguration(BaseModel):
    acceptedOutputModes: list[str] | None = None
    historyLength: conint(ge=0) | None = None
    returnImmediately: bool | None = False
    """
    false (default): wait for a terminal or interrupted state. true: return SUBMITTED at once and poll/subscribe.
    """


class SendMessageRequest(BaseModel):
    tenant: str | None = None
    """
    MUST match the AgentInterface.tenant of the callee's card.
    """
    message: Message
    configuration: SendMessageConfiguration | None = None
    metadata: dict[str, Any] | None = None


class SendMessageResponse1(BaseModel):
    """
    Exactly one of task or message.
    """

    task: Task
    message: Message | None = None


class SendMessageResponse2(BaseModel):
    """
    Exactly one of task or message.
    """

    task: Task | None = None
    message: Message


class SendMessageResponse(RootModel[SendMessageResponse1 | SendMessageResponse2]):
    root: SendMessageResponse1 | SendMessageResponse2
    """
    Exactly one of task or message.
    """


class GetTaskRequest(BaseModel):
    tenant: str | None = None
    id: str
    historyLength: conint(ge=0) | None = None


class ListTasksRequest(BaseModel):
    """
    Results are ALWAYS scoped to the authenticated caller's own tasks (state-mapping.md §5).
    """

    tenant: str | None = None
    filter: str | None = None
    pageSize: conint(ge=1) | None = None
    pageToken: str | None = None


class ListTasksResponse(BaseModel):
    tasks: list[Task] | None = None
    nextPageToken: str | None = None


class CancelTaskRequest(BaseModel):
    tenant: str | None = None
    id: str


class SubscribeToTaskRequest(BaseModel):
    tenant: str | None = None
    id: str


class StreamResponse1(BaseModel):
    """
    One SSE frame payload. Exactly one variant.
    """

    task: Task
    message: Message | None = None
    statusUpdate: TaskStatusUpdateEvent | None = None
    artifactUpdate: TaskArtifactUpdateEvent | None = None


class StreamResponse2(BaseModel):
    """
    One SSE frame payload. Exactly one variant.
    """

    task: Task | None = None
    message: Message
    statusUpdate: TaskStatusUpdateEvent | None = None
    artifactUpdate: TaskArtifactUpdateEvent | None = None


class StreamResponse3(BaseModel):
    """
    One SSE frame payload. Exactly one variant.
    """

    task: Task | None = None
    message: Message | None = None
    statusUpdate: TaskStatusUpdateEvent
    artifactUpdate: TaskArtifactUpdateEvent | None = None


class StreamResponse4(BaseModel):
    """
    One SSE frame payload. Exactly one variant.
    """

    task: Task | None = None
    message: Message | None = None
    statusUpdate: TaskStatusUpdateEvent | None = None
    artifactUpdate: TaskArtifactUpdateEvent


class StreamResponse(
    RootModel[StreamResponse1 | StreamResponse2 | StreamResponse3 | StreamResponse4]
):
    root: StreamResponse1 | StreamResponse2 | StreamResponse3 | StreamResponse4
    """
    One SSE frame payload. Exactly one variant.
    """


class Datum(BaseModel):
    field_type: str = Field(..., alias='@type')


class JsonRpcError(BaseModel):
    code: int
    message: str
    data: list[Datum] | None = None
    """
    Each element carries an @type key (ProtoJSON Any).
    """


class Method(StrEnum):
    """
    Bare PascalCase — NOT 'message/send' (0.x) and NOT 'a2a.SendMessage'.
    """

    SendMessage = 'SendMessage'
    SendStreamingMessage = 'SendStreamingMessage'
    GetTask = 'GetTask'
    ListTasks = 'ListTasks'
    CancelTask = 'CancelTask'
    SubscribeToTask = 'SubscribeToTask'
    GetExtendedAgentCard = 'GetExtendedAgentCard'


class JsonRpcRequest(BaseModel):
    jsonrpc: Literal['2.0']
    id: str | int
    method: Method
    """
    Bare PascalCase — NOT 'message/send' (0.x) and NOT 'a2a.SendMessage'.
    """
    params: dict[str, Any] | None = None


class JsonRpcResponse(BaseModel):
    jsonrpc: Literal['2.0']
    id: str | int | None
    result: Any | None = None
    error: JsonRpcError | None = None
