# generated by datamodel-codegen:
#   filename:  agent-card.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, constr


class ProtocolBinding(StrEnum):
    """
    Open string. Core values: JSONRPC, GRPC, HTTP+JSON. Fuze v1 permits only JSONRPC.
    """

    JSONRPC = 'JSONRPC'
    GRPC = 'GRPC'
    HTTP_JSON = 'HTTP+JSON'


class AgentInterface(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    """
    Absolute URL of this interface. In-cluster Fuze interfaces use service DNS (http://a2a-<repo>.fuzeagent.svc.cluster.local:8080/rpc); externally-published ones MUST be https:// through the Cloudflare tunnel.
    """
    protocolBinding: ProtocolBinding
    """
    Open string. Core values: JSONRPC, GRPC, HTTP+JSON. Fuze v1 permits only JSONRPC.
    """
    tenant: str | None = None
    """
    Opaque routing id when several agents sit behind one endpoint. The Fuze shared server sets this to the serving repo slug so one ingress can front many product agents. When set, clients MUST echo it in the request `tenant` field.
    """
    protocolVersion: constr(pattern=r'^\d+\.\d+$')
    """
    A2A protocol Major.Minor exposed at this URL (NOT the agent version). Fuze v1 freezes on "1.0".
    """


class AgentProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    organization: constr(min_length=1)


class AgentExtension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uri: AnyUrl
    description: str | None = None
    required: bool | None = None
    params: dict[str, Any] | None = None


class SecurityRequirement(RootModel[dict[str, list[str]]]):
    """
    Map of security scheme name -> list of required scopes.
    """

    root: dict[str, list[str]]


class Location(Enum):
    query = 'query'
    header = 'header'
    cookie = 'cookie'


class ApiKeySecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    location: Location
    name: str


class HttpAuthSecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    scheme: str
    bearerFormat: str | None = None


class Oauth2SecurityScheme(BaseModel):
    description: str | None = None
    flows: dict[str, Any]
    oauth2MetadataUrl: AnyUrl | None = None


class OpenIdConnectSecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    openIdConnectUrl: AnyUrl


class MtlsSecurityScheme(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None


class SecurityScheme(BaseModel):
    """
    ProtoJSON oneof wrapper — exactly one variant key.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    apiKeySecurityScheme: ApiKeySecurityScheme | None = None
    httpAuthSecurityScheme: HttpAuthSecurityScheme | None = None
    oauth2SecurityScheme: Oauth2SecurityScheme | None = None
    openIdConnectSecurityScheme: OpenIdConnectSecurityScheme | None = None
    mtlsSecurityScheme: MtlsSecurityScheme | None = None


class AgentCardSignature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protected: str
    """
    base64url-encoded protected JWS header.
    """
    signature: str
    """
    base64url-encoded signature.
    """
    header: dict[str, Any] | None = None


class AgentCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    streaming: bool | None = None
    pushNotifications: bool | None = None
    extendedAgentCard: bool | None = None
    extensions: list[AgentExtension] | None = None


class AgentSkill(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[a-z0-9_-]+$')
    """
    MUST equal the `role` key of the source role.json. This is the join key that lets the adapter resolve a skill back to a role manifest.
    """
    name: constr(min_length=1)
    description: constr(min_length=1)
    tags: list[str] = Field(..., min_length=1)
    examples: list[str] | None = None
    inputModes: list[str] | None = None
    outputModes: list[str] | None = None
    securityRequirements: list[SecurityRequirement] | None = None


class FuzeA2AAgentCard(BaseModel):
    """
    JSON Schema for the A2A AgentCard as served at /.well-known/agent-card.json. Faithful to the ProtoJSON (camelCase) serialization of message AgentCard in lf.a2a.v1 (a2a.proto, A2A spec 1.0.0). The `fuze` profile below adds REQUIRED family constraints on top of the open standard; a card that satisfies this schema is by construction a valid A2A 1.0 AgentCard.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    """
    Human readable agent name. Fuze projection: `<Repo> <role> agent`, e.g. 'FuzePlan planning agent'.
    """
    description: constr(min_length=1)
    """
    What this agent is for, in caller-facing terms. Callers route on this text, so it MUST describe outcomes the agent delivers, not the tools it holds.
    """
    supportedInterfaces: list[AgentInterface] = Field(..., min_length=1)
    """
    Ordered list of interfaces; the FIRST entry is the preferred one. A2A 1.0 replaced 0.x `url` + `preferredTransport` with this list — there is no top-level url field.
    """
    provider: AgentProvider
    version: constr(pattern=r'^\d+\.\d+\.\d+(?:[-+].*)?$')
    """
    Version OF THE AGENT (not of the A2A protocol). SemVer. Projected from the contract version of the serving repo's role set.
    """
    documentationUrl: AnyUrl | None = None
    iconUrl: AnyUrl | None = None
    capabilities: AgentCapabilities
    securitySchemes: dict[str, SecurityScheme] | None = Field(None, min_length=1)
    """
    Map of scheme name -> SecurityScheme. NOTE the ProtoJSON oneof wrapper: the value is an object with exactly one key naming the scheme variant (e.g. {"openIdConnectSecurityScheme": {...}}). This is NOT the OpenAPI securityScheme shape.
    """
    securityRequirements: list[SecurityRequirement] | None = None
    """
    Requirements for contacting the agent. Entries are OR'ed; schemes within an entry are AND'ed.
    """
    defaultInputModes: list[str] = Field(..., min_length=1)
    """
    Media types accepted across all skills. Fuze v1 baseline: ["text/plain", "application/json"].
    """
    defaultOutputModes: list[str] = Field(..., min_length=1)
    """
    Media types produced. Fuze v1 baseline: ["text/plain", "application/json"].
    """
    skills: list[AgentSkill] = Field(..., min_length=1)
    """
    DERIVED from agent-templates/roles/*/role.json. See card-projection.md. Hand-authoring skills is a contract violation.
    """
    signatures: list[AgentCardSignature] | None = None
    """
    JWS signatures over the canonicalized card (RFC 7515 JSON serialization). OPTIONAL in A2A; see the Fuze profile for when it is REQUIRED.
    """
